name: Makefile CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Update package list
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libglew-dev
      
    - name: Download libprimis.lib artifact
      uses: dawidd6/action-download-artifact@v3.1.1
      with:
        workflow: makefile.yml
        name: libprimis-linux
        path: ./
        repo: project-imprimis/libprimis
        branch: main

    - name: Install libprimis
      run: sudo cp ./libprimis.so /usr/lib/libprimis.so
      
    - name: Build
      run: make -j4
      
    - name: Clean files
      run: make remove-build-files
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: imprimis-linux
        path: ./*
